name: PyPi package release

on:
  workflow_dispatch:
    inputs:
      api_pypi:
        description: 'PyPI API token'
        required: true

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies for build and publish
        run: |
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ github.event.inputs.api_pypi }}
        run: |
          twine upload --repository pypi dist/*
