name: Code Improvements

on: push
  
jobs:
  code_improvement:
    name: Auto Code Format & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort autoflake

      - name: Run Flake8 for Critical Errors
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Remove Unused Imports and Variables with Autoflake
        run: autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports .

      - name: Sort Imports with Isort
        run: isort . --profile black

      - name: Format Code with Black
        run: black . --line-length 120

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
