name: Code Improvements

on: [push, pull_request]

jobs:
  code_improvement:
    name: Auto Format & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff to Format and FIX
        run: ruff format . && ruff check . --fix --exit-zero
      
      - name: Run Ruff to Lint
        run: ruff check .

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(bot): auto-format and lint code"
